### ISSUE TITLE
Unnecessary question mark

### ISSUE THREAD

**Issue by mnik01** [stanleyogada/react-rc-carousel#1]
There is an unnecessary question mark in this place:

https://github.com/stanleyogada/react-rc-carousel/blob/bcaf6abd6bdfed41619cd2ed0b5a42ba4e273647/src/hooks/useControls.ts#LL33C17-L33C17

because you already have checked if container exists in line higher

**Comment by stanleyogada** [comment]
Thanks @mnik01
